function result = gameWon(board, playersymbol);
    result = (isequal(board{1,1},board{1,2},playersymbol) && isequal(board{1,1},board{1,3},playersymbol))|| ...
        (isequal(board{2,1},board{2,2},playersymbol) && isequal(board{2,1},board{2,3},playersymbol))|| ...
        (isequal(board{3,1},board{3,2},playersymbol) && isequal(board{3,1},board{3,3},playersymbol))|| ...
        (isequal(board{1,1},board{2,1},playersymbol) && isequal(board{1,1},board{3,1},playersymbol))|| ...
        (isequal(board{1,2},board{2,2},playersymbol) && isequal(board{1,2},board{3,2},playersymbol))|| ...
        (isequal(board{1,3},board{2,2},playersymbol) && isequal(board{1,3},board{3,1},playersymbol))|| ...
        (isequal(board{1,1},board{2,2},playersymbol) && isequal(board{1,1},board{3,3},playersymbol))|| ...
        (isequal(board{1,3},board{2,3},playersymbol) && isequal(board{1,3},board{3,3},playersymbol));
end


